# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bliss-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bliss-app
  pod 'SnapKit'
  pod 'Moya'
  pod 'RealmSwift', '5.5.0'

end
